### PR TITLE
Rename openfoam->additivefoam

### LINKED ISSUE #2: Update outdated OpenFOAM usage in portions of UQ workflows
So, we've got a few locations in the UQ workflow that still reference aspects of AdditiveFOAM as OpenFOAM. For example in the Stage1 `setup.py` file we call the cases `openfoam`. A more descriptive name would be to update these to `additivefoam` even if it's a bit longer.

### PR DESCRIPTION
**Pull request by streeve**
I was in a seminar so I did some search/replace

I left existing (e.g. Frontier) filepaths as "openfoam"

Closes #2

### CODE REVIEW

**Comment by mtitov** [comment]
added renaming for leftovers within the EnTK section. LGTM!

**Review by rcarson3 — APPROVED** [review]
LGTM thanks @streeve for tackling this

**Comment by streeve** [comment]
@MattRolchigo can you review and merge if you’re happy with it?

**Comment by streeve** [comment]
ping @MattRolchigo

**Review by MattRolchigo — APPROVED** [review]

**Pull request merged**
